(function(A,E,B){if(A.USR==B){A.USR={}}var C=A.USR;if(!C.initialized){C.$=function(D){return E.getElementById(D)
};C.show=function(){for(var F=0,D=arguments.length;F<D;F++){this.$(arguments[F]).style.display="block"
}};C.hide=function(){for(var F=0,D=arguments.length;F<D;F++){this.$(arguments[F]).style.display="none"
}};C.addCss=function(G){var D=E.getElementsByTagName("head")[0],F=E.createElement("style");F.type="text/css";
if(F.styleSheet){F.styleSheet.cssText=G}else{rules=E.createTextNode(G);F.appendChild(rules)}D.appendChild(F)
};C.getCookie=function(H){var F=H+"=",D=E.cookie.split(";"),I;for(var G=0;G<D.length;G++){I=D[G].trim();
if(I.indexOf(F)===0){return I.substring(F.length,I.length)}}return null};C.getVisitorId=function(){var D=C.getCookie("__utma");
return(D?D.split(/\./)[1]:"")};C.stringify=function(J){if(typeof JSON==="undefined"||!JSON||typeof JSON.stringify!=="function"){var H,G,F,I,D;
switch(typeof J){case"string":return C.quote(J);case"number":return isFinite(J)?String(J):"null";case"boolean":case"null":return String(J);
case"object":if(!J){return"null"}D=[];if(Object.prototype.toString.apply(J)==="[object Array]"){I=J.length;
for(H=0;H<I;H+=1){D[H]=C.stringify(J[H])||"null"}F=D.length===0?"[]":"["+D.join(",")+"]";return F}for(G in J){if(Object.hasOwnProperty.call(J,G)){F=C.stringify(J[G]);
if(F){D.push(C.quote(G)+":"+F)}}}F=D.length===0?"{}":"{"+D.join(",")+"}";return F}}else{return JSON.stringify(J)
}};C.quote=function(D){var F=C.escapable;F.lastIndex=0;return F.test(D)?'"'+D.replace(F,function(G){var H=C.meta[G];
return typeof H==="string"?H:"\\u"+("0000"+G.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+D+'"'};C.escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
C.meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};C.lang={de:["Ik wil op","powered by"],en:["I want to","powered by"],es:["Quiero quieres a","potencia por"]};
C.isIE6=function(){return(E.body.filters&&parseInt(navigator.appVersion.split("MSIE")[1],10)<7)};C.isEmptyObject=function(F){if(!F){return true
}for(var D in F){return false}return true};C.hasPropInObject=function(G,H,D){var F=G[H];if(F&&(!D||typeof F===D)){return true
}return false};C.doPngFixOnBgImg=function(H){if(H&&C.isIE6()){var G=H.style,D=H.currentStyle,K="/img/x.gif",J="scale",F=D.backgroundImage,I=F.substring(5,F.length-2);
if(D.backgroundRepeat=="no-repeat"){J="crop"}G.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+I+"', sizingMethod='"+J+"')";
G.backgroundImage="url("+K+")";G.backgroundPositionX=D.backgroundPositionX;G.backgroundPositionY=D.backgroundPositionY
}};C.initialized=true}C.Main=(function(R){var Q=this,P,I,D,J,N,G,M,H,F=false;R=R||{};R.type=R.type||"button";
R.host=R.host||(R.company+".userrules.com");if(R.type==="button"){R.placement=R.placement||"left";R.orientation=(R.placement==="top"||R.placement==="bottom"?"horz":"vert");
R.bgColor=R.color[0]||"#32312E";R.hlColor=R.color[1]||"#62615E"}R.lang=(!!R.lang&&/(en|es|de)/gi.test(R.lang)?R.lang:"en");
R.width=752;P=""+".usr-feedback-button {background-color: "+R.bgColor+'; background-image:url("https://dtkm4pd19nw6z.cloudfront.net/img/feedback_trans_tab.png"); background-repeat:no-repeat; color: #FFF; cursor:pointer; overflow: hidden; position: fixed; text-indent: -100000px; z-index: 100000;} .usr-feedback-button:hover {background-color: '+R.hlColor+";} .usr-feedback-button.vert { background-position:0 0; height:102px; top: 40%; width:42px;} .usr-feedback-button.vert.left {left: 0; margin-left: -7px;} .usr-feedback-button.vert.right {right: 0; margin-right: -7px;} .usr-feedback-button.horz {background-position: 0 -102px; height: 38px; left: 45%; width: 102px;} .usr-feedback-button.horz.top {top: 0; margin-top: -7px;} .usr-feedback-button.horz.bottom {bottom: 0; margin-bottom: -7px;} "+"#usrFeedbackModalContainer {display: none; height: 100%; left: 0; position: absolute; top: 0; width: 100%; z-index: 1000000 !important;} #usrFeedbackModalOverlay {background: rgba(255, 255, 255, 0.75); display: none; height: 100%; left: 0; position: absolute; top: 0; width: 100%; z-index: 999999 !important} .lte7 #usrFeedbackModalOverlay {background: #fff; filter: alpha(opacity=75);} #usrFeedbackModal {background: transparent; border: 0 none; font-family: arial,sans-serif; display: block; height: 600px; margin: 0 auto; position: relative; width: 752px; z-index: 1000001 !important;} "+'#usrModalHeader {-moz-border-radius: 4px 4px 0 0; -webkit-border-radius: 4px 4px 0 0; background: #eaeaea; background: -webkit-gradient(linear, left top, left bottom, from(#fafafa), to(#dadada)); background: -moz-linear-gradient(top,  #fafafa,  #dadada); border: 1px solid #acacac; border-bottom-color: #d2d2d2; border-radius: 4px 4px 0 0; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#fafafa", endColorstr="#dadada"); height: 40px; position: relative;} .lte7 #usrModalHeader {zoom: 1;} #usrModalHeader h2 {float: left; font-size: 20px; font-weight: normal; line-height: 30px; margin: 0; padding-top: 5px; text-indent: 15px;} .usr-close {-moz-transition: none; -webkit-transition: none; background: url("https://dtkm4pd19nw6z.cloudfront.net/img/widget/close.png") no-repeat; cursor: pointer; display: block; height: 30px; outline: 0; position: absolute; right: -15px; top: -15px; transition: none; width: 30px;} .lte7 .usr-close {float: right; margin: 5px 10px 0 0; position: static;} .usr-close:hover {background-position: 0 -30px; border-bottom: 0;} #usrModalHeader .clear {clear: both;} '+"#usrFeedbackIFrame {background: transparent; display: none;} #usrLoading {-moz-border-radius: 0 0 4px 4px; -webkit-border-radius: 0 0 4px 4px; -moz-box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); -webkit-box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); background: #FAFBFC; border: 1px solid #acacac; border-radius: 0 0 4px 4px; border-top: 0; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); color: #CF4236; font-size: 18px; font-weight: bold; padding: 15px 0 20px; text-align: center;}";
C.addCss(P);I=["access=remote","version=2.0","lang="+R.lang,"visitorId="+(typeof R.getVisitorId==="function"?R.getVisitorId():"")];
if(typeof R.getAdditionalParams==="function"){jsParams=R.getAdditionalParams();if(typeof jsParams==="object"){jsParams=C.stringify(jsParams)
}if(typeof jsParams==="string"){I.push("additionalParams="+encodeURIComponent(jsParams))}}G=R.sso;if(!C.isEmptyObject(G)&&C.hasPropInObject(G,"uid","string")&&C.hasPropInObject(G,"un","string")&&C.hasPropInObject(G,"uem","string")&&C.hasPropInObject(G,"sign","string")){I.push.apply(I,["sso=true","uid="+G.uid,"un="+G.un,"uem="+G.uem,"uimg="+(G.uimg||""),"sign="+G.sign])
}M=("https:"===E.location.protocol);D="http"+(M?"s":"")+"://"+R.host+"/feedback/new?"+I.join("&");J=""+(R.type==="button"?'<a href="javascript: void(0);" id="usrFeedbackButton" class="usr-feedback-button '+R.orientation+" "+R.placement+'">FEEDBACK</a>':"")+'<div id="usrFeedbackModalContainer">'+'<div id="usrFeedbackModal" class="'+R.lang+'">'+'<div id="usrModalHeader"><h2>Share a feedback</h2><a id="usrFeedbackModalClose" class="usr-close"></a><div class="clear"></div></div>'+'<div id="usrLoading">Loading...</div>'+'<iframe id="usrFeedbackIFrame" allowTransparency="true" scrolling="no" frameborder="0" src="" width="'+R.width+'px" height="100%" style="display: none; height: 100%; width: '+R.width+'px;"></iframe>'+"</div>"+'</div><div id="usrFeedbackModalOverlay"></div>';
if(E.body){var K=E.createDocumentFragment(),L=E.createElement("div");L.innerHTML=J;while(L.firstChild){K.appendChild(L.firstChild)
}E.body.insertBefore(K,E.body.childNodes[0])}else{E.write(J)}H=C.$("usrFeedbackButton");if(H){C.doPngFixOnBgImg(H);
H.onclick=function(){C.Main.show();return false}}C.$("usrFeedbackModalClose").onclick=function(){C.Main.hide();
return false};var N=function(){var V=E.documentElement.scrollTop||E.body.scrollTop,U=E.documentElement.scrollHeight,S=A.innerHeight||E.documentElement.clientHeight,W=A.innerWidth||E.documentElement.clientWidth,T="px";
C.$("usrFeedbackModalContainer").style.height=C.$("usrFeedbackModalOverlay").style.height=U+T;C.$("usrFeedbackModal").style.top=(V+(S*0.125))+T
},O=function(S){S=S||window.event;if(S.keyCode==27){C.Main.hide()}};return{show:function(T){var U=C.$("usrFeedbackIFrame"),S=this;
N();C.show("usrLoading","usrFeedbackModalOverlay","usrFeedbackModalContainer");U.setAttribute("src",D+(T?"&title="+T:""));
if(U.addEventListener){U.addEventListener("load",S.onLoad,false)}else{if(U.attachEvent){U.attachEvent("onload",S.onLoad)
}}if(!F){if(E.addEventListener){E.addEventListener("keyup",O,false)}else{if(E.attachEvent){E.attachEvent("onkeyup",O)
}}F=true}},hide:function(){C.hide("usrFeedbackModalOverlay","usrFeedbackModalContainer","usrFeedbackIFrame");
var T=C.$("usrFeedbackIFrame"),S=this;if(T.addEventListener){T.removeEventListener("load",S.onLoad,false)
}else{if(T.attachEvent){T.attachEvent("onload",S.onLoad)}}},onLoad:function(){C.hide("usrLoading");C.show("usrFeedbackIFrame")
}}})(A._usrp)})(window,document);